trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals DESKTOP-F9L7I0T

strategy:
  matrix:
    Python312:
      python.version: '3.12'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: $(System.DefaultWorkingDirectory)
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-$(python.version).zip
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'FilePath'
    TargetPath: 'C:\Devops_azure'
    
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'drop'
#     publishLocation: 'Container'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'

# - script: |
#     echo "Deploying to local agent directory C:\Devops_azure"
#     xcopy /E /I /H $(System.DefaultWorkingDirectory) "C:\Devops_azure\simple-python-website"
#   displayName: 'Deploy to Local Agent'


